Recording
SiarheiBalt/MusicStudio pull request #1
Opened 2021-10-14 06:03 UTC by SiarheiBalt

2021-10-14 09:00 UTC, Aliaksandrlosich requested changes

2021-10-14 09:00 UTC, Aliaksandrlosich commented on package.json
> +    "redax": "0.0.0",
Что это за зависимость??

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/App.js
> +          <Route path='/main' component={Main} />
Роуты в отдельный файл routers

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/functions/date.js
> +
Обычно называют папку utils или helpers. А то, что это вынес это отдельно, это лайк

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/functions/date.js
> +    2: 'Февраль',
А в date-fns нет локалей для rus? Посмотри библиотеку, возможно там и строки для день/месяц месяц можно взять

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/components/commons/ReserveForm/ReserveForm.jsx
> +import cl from './ReserveForm.module.css';
cl такое себе сокращение для стилей

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/components/commons/ReserveForm/ReserveForm.jsx
> +        <select value={select} onChange={selectChange}>
Селект так же можно превратит в компонент.

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/components/commons/ReserveForm/ReserveForm.jsx
> +          <option value='10'>10:00 до 12:00</option>
Копипаст для опций. Можно собрать через map. при этом очень строго забито время ребят. Сделай более динамический выбор времени. Например, ты передаешь начала работы,  и конец. А так же шаг. Однако мне не нравится сам подход, выбора времени

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/components/commons/authForm/AuthorizationForm.jsx
> +        <span>Login</span> <Input />
Любой элемент, всегда должен содержать классы. Так же у тебя ведь сайт на русском, а тут login на англ

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/components/commons/authForm/AuthorizationForm.jsx
> +        <span>Password</span> <Input />
Весь статический текст который ты пишешь в jsx, выноси в переменные. В качестве нейминга, можно использовать названия класса элемента, где оно находится. Зачем спросишь ты? Во первых, это упрощает изменение текста. Не нужно лазить по в компоненте. Знаешь его класс, строку поменял, готово. Так же, такой подход используют для поддержки разных локализаций. Вместо обьекта с русским языком, легко становится обьект с английским, и это всего за пару минут

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/App.js
> +          <Route exact path='/MusicStudio'>
Пути с маленькой буквы. И желательно одно слово. тут бы хватило и studio

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/components/commons/button/Button.jsx
> +export const Button = ({ action, onClick, disabled }) => {
Используй PropTypes

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/components/commons/input/Input.jsx
> +      type={type ? type : 'text'}
Без сложной логики в jsx. в jsx только конечный результат

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/components/commons/shedule/Shedule.jsx
> +      {timeData.map((day, i) => {
Вынеси логику из jsx

2021-10-14 09:00 UTC, Aliaksandrlosich commented on src/components/commons/shedule/dayShedule/DayShedule.jsx
> +
Тяжело читается твоя компонента.

2021-10-21 16:28 UTC, SiarheiBalt commented on package.json
> +    "redax": "0.0.0",
Удалил

2021-10-21 16:28 UTC, SiarheiBalt commented on src/App.js
> +          <Route path='/main' component={Main} />
Создал отдельную папку, и файл

2021-10-21 16:29 UTC, SiarheiBalt commented on src/functions/date.js
> +
Переименовал в utils

2021-10-21 16:30 UTC, SiarheiBalt commented on src/functions/date.js
> +    2: 'Февраль',
Да, есть. Взял строки для месяца, дня недели

2021-10-21 16:31 UTC, SiarheiBalt commented on src/components/commons/ReserveForm/ReserveForm.jsx
> +import cl from './ReserveForm.module.css';
Пока не переименовывал.

2021-10-21 16:31 UTC, SiarheiBalt commented on src/components/commons/ReserveForm/ReserveForm.jsx
> +        <select value={select} onChange={selectChange}>
Создал отдельный компонент

2021-10-21 16:33 UTC, SiarheiBalt commented on src/components/commons/ReserveForm/ReserveForm.jsx
> +          <option value='10'>10:00 до 12:00</option>
Собрал через map. Сделал более динамичный выбор времени, изменил шаг времени на 1час.

2021-10-21 16:34 UTC, SiarheiBalt commented on src/components/commons/authForm/AuthorizationForm.jsx
> +        <span>Login</span> <Input />
Авторизацию пока не трогал, для этого у меня другая ветка.

2021-10-21 16:35 UTC, SiarheiBalt commented on src/components/commons/authForm/AuthorizationForm.jsx
> +        <span>Password</span> <Input />
Вынес статический текст в переменные. Пока не везде, т.к. будут конфликты в ветках

2021-10-21 16:36 UTC, SiarheiBalt commented on src/App.js
> +          <Route exact path='/MusicStudio'>
Исправлено

2021-10-21 16:36 UTC, SiarheiBalt commented on src/components/commons/button/Button.jsx
> +export const Button = ({ action, onClick, disabled }) => {
Начал использовать PropTypes

2021-10-21 17:02 UTC, SiarheiBalt commented on src/components/commons/input/Input.jsx
> +      type={type ? type : 'text'}
Исправил

2021-10-21 17:03 UTC, SiarheiBalt commented on src/components/commons/shedule/Shedule.jsx
> +      {timeData.map((day, i) => {
Вынес

2021-10-21 17:03 UTC, SiarheiBalt commented on src/components/commons/shedule/dayShedule/DayShedule.jsx
> +
Переименовал

2021-10-22 09:41 UTC, Aliaksandrlosich commented
![image](https://user-images.githubusercontent.com/43148660/138432378-6882e40c-9e74-4978-85b5-df71cff6791c.png)

2021-10-22 09:50 UTC, Aliaksandrlosich commented
Реализуй приватный роутинг, для авторизированных роутов 
![image](https://user-images.githubusercontent.com/43148660/138433799-db958ba4-2833-44b3-a6a5-90003cd979bd.png)

2021-10-22 10:15 UTC, Aliaksandrlosich commented
![image](https://user-images.githubusercontent.com/43148660/138436773-8be47ee3-33f1-47a8-a655-81aa0d76ad55.png)
Это не к этому пр, но будет ли функционал отмены брони в личном кабинете?

2021-10-22 10:24 UTC, Aliaksandrlosich commented
![image](https://user-images.githubusercontent.com/43148660/138437934-d963eba8-3ba6-417f-9f4e-fee4b105afc6.png)
Много всяких попапов плоховато. Что бы сделать более по новому, можно реализовать так. Пользователь может кликать на свободное время,оно станет условно синим/серым/затемнённое(от дизайна отталкиваться будем). Пользователь может несколько раз кликать по разному времени, далее он может нажать зарезервировать. И сохранится весь его промежуток. 
Тем самым мы удалим лишний скачок в попапе, а так же выбор периода времени. Если что-то не понятно, пиши

2021-10-22 12:28 UTC, Aliaksandrlosich reviewed
Закрываю ревью в этой ветке. Т.к. Это уже есть в ветке demo

2021-10-22 12:28 UTC, Aliaksandrlosich commented on src/components/commons/dateSelect/DateSelect.jsx
> +  const text = ' Выберите дату, либо кликните на ближайший день ниже';
Пробел в стринге.

2021-10-22 12:28 UTC, Aliaksandrlosich commented on src/components/commons/dateSelect/DateSelect.jsx
> +    <div className={cl.container}>
Можно использовать деструктуризацию, что б не тягать cl.

2021-10-26 09:11 UTC, closed without merging