Demo
SiarheiBalt/MusicStudio pull request #2
Opened 2021-10-22 11:23 UTC by SiarheiBalt

2021-10-22 12:33 UTC, Aliaksandrlosich commented
Назначь на меня ревью

2021-10-26 09:44 UTC, Aliaksandrlosich requested changes

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/authForm/AuthorizationForm.jsx
> +import { useState } from 'react';
Поддерживай порядок импортов.
Сначала либы
-пробел
твои компоненты, функции, константы.
-пробел
стили css

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/authForm/AuthorizationForm.jsx
> +      {formState === typeForm.registration ? (
Такое не стоит делать в jsx. До ретурна нужно сделать все действия. В ретурне только готовые переменные

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/authForm/AuthorizationForm.jsx
> +      {!!error && (
Вместо отдельных дивов, можно сделать панельку. Куда ты можешь передавать свой статус

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/authForm/LoginRegisterationForm.jsx
> +      .typeError('Должно быть строкой')
Странная ошибка, должно быть строкой. Простой человек не поймёт

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/authForm/LoginRegisterationForm.jsx
> +      {({
Что тут происходит? Почему это происходит в jsx

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/authForm/LoginRegisterationForm.jsx
> +              {type === typeForm.login ? 'входа' : 'регистрации'}
отдельно

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/input/Input.jsx
> +  const inputType = type ? type : 'text';
Вместо этого, можно сделать дефолтные константы, сразу в параметрах функции

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/button/Button.jsx
> +      {action}
Корректнее было б просто text/label для кнопки, а не action

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/redux/reducers/reserveTimeReducer.js
> +        [`${type}`]: state[`${type}`].map((item) => {
Это можно было сделать до ретурна. Слишком усложнена логика

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/dateSelect/DateSelect.jsx
> +  const staticText = 'Выберите дату, либо кликните на ближайший день ниже';
Некоректный нейминг

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/reserveItem/modal/Modal.jsx
> +    let array = selectedHours.concat();
Нейминг плохой. То что это массив хорошо, но вот что за массив

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/reserveItem/modal/Modal.jsx
> +  const hourClick = (hour) => {
Стоит поработать над этой функцией. Она слишком смешенная, из-за чего тяжело читается

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/reserveItem/modal/hour/Hour.jsx
> +    ? `${cl.time} ${cl.tooltip} ${isSelected ? cl.gray : cl.green}`
Создай константы из этих стилей. Так же, можно посмотреть в сторону classNames либы

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/container/main/Main.jsx
> +  const isAuth = data.isAuth;
const {isAuth} = data
 можно использовать деструктуризацию, чем явное присваивание

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/commons/shedule/Shedule.jsx
> +  const days = timeData.map((day, i) => {
В нейминге стоит указать что за именно days.

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/container/main/contacts/Contacts.jsx
> +      <ul className={'list'}>
лишние скобки

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/container/main/serviceTypes/ServiceType.jsx
> +        <h2 className={'title'}>{titleRecordText}</h2>
зачем тебе фигурные скобки?

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/container/profile/Profile.jsx
> +  if (!isAuth) return <Redirect to="Login" />;
Используй приватный роутинг

2021-10-26 09:44 UTC, Aliaksandrlosich commented on src/components/container/recording/Recording.jsx
> +      key={i}
В качестве ключа, лучше не использовать обычные индексы. Пример: если у тебя от 0 до 10 ключи, что-то происходит, и элемент со вторым ключом удалется, тогда перерендерится следом всё остальное после 2 ключа, ибо происходит их смещение. не 0,1,3,4...10, а 0,1,2,3...9

2021-10-28 11:36 UTC, SiarheiBalt commented on src/components/commons/authForm/AuthorizationForm.jsx
> +import { useState } from 'react';
Где видел исправил, в дальнейшем буду поддерживать

2021-10-28 11:38 UTC, SiarheiBalt commented on src/components/commons/authForm/AuthorizationForm.jsx
> +      {formState === typeForm.registration ? (
Понял, так и делаю. Возможно не увидел

2021-10-28 11:39 UTC, SiarheiBalt commented on src/components/commons/authForm/AuthorizationForm.jsx
> +      {!!error && (
Создал отдельный компонент для отображения статусов

2021-10-28 11:39 UTC, SiarheiBalt commented on src/components/commons/authForm/LoginRegisterationForm.jsx
> +      .typeError('Должно быть строкой')
Исправил

2021-10-28 11:53 UTC, SiarheiBalt commented on src/components/commons/authForm/LoginRegisterationForm.jsx
> +      {({
Вынес до ретурна. Разделил общую компоненту для регистрации, авторизации на две. Логика при это стала более читаема. Использовал formik, yup. Поглядеть на другие варианты реализации?

2021-10-28 11:54 UTC, SiarheiBalt commented on src/components/commons/authForm/LoginRegisterationForm.jsx
> +              {type === typeForm.login ? 'входа' : 'регистрации'}
Удалил компоненту

2021-10-28 11:55 UTC, SiarheiBalt commented on src/components/commons/input/Input.jsx
> +  const inputType = type ? type : 'text';
Использовал дефолтную константу

2021-10-28 11:55 UTC, SiarheiBalt commented on src/components/commons/button/Button.jsx
> +      {action}
исправил

2021-10-28 11:57 UTC, SiarheiBalt commented on src/redux/reducers/reserveTimeReducer.js
> +        [`${type}`]: state[`${type}`].map((item) => {
Разделил редюсер на два, вынес до ретурна (логика стала понятней). Я думаю это пока не конечный вариант, т.к. будет сервер.

2021-10-28 11:57 UTC, SiarheiBalt commented on src/components/commons/dateSelect/DateSelect.jsx
> +  const staticText = 'Выберите дату, либо кликните на ближайший день ниже';
Исправил

2021-10-28 11:58 UTC, SiarheiBalt commented on src/components/commons/reserveItem/modal/Modal.jsx
> +    let array = selectedHours.concat();
Исправил

2021-10-28 12:41 UTC, SiarheiBalt commented on src/components/commons/reserveItem/modal/Modal.jsx
> +  const hourClick = (hour) => {
Логику не менял. переименовал переменные, условие вынес. Если только через редюсер, сделать свойство isSelected?

2021-10-28 12:42 UTC, SiarheiBalt commented on src/components/commons/reserveItem/modal/hour/Hour.jsx
> +    ? `${cl.time} ${cl.tooltip} ${isSelected ? cl.gray : cl.green}`
Установил, применил библиотеку classNames

2021-10-28 12:43 UTC, SiarheiBalt commented on src/components/container/main/Main.jsx
> +  const isAuth = data.isAuth;
Использовал деструктуризацию

2021-10-28 12:47 UTC, SiarheiBalt commented on src/components/commons/shedule/Shedule.jsx
> +  const days = timeData.map((day, i) => {
Исправил

2021-10-28 12:47 UTC, SiarheiBalt commented on src/components/container/main/contacts/Contacts.jsx
> +      <ul className={'list'}>
Исправлено

2021-10-28 12:48 UTC, SiarheiBalt commented on src/components/container/main/serviceTypes/ServiceType.jsx
> +        <h2 className={'title'}>{titleRecordText}</h2>
Удалил

2021-10-28 12:53 UTC, SiarheiBalt commented on src/components/container/profile/Profile.jsx
> +  if (!isAuth) return <Redirect to="Login" />;
Исправил

2021-10-28 12:54 UTC, SiarheiBalt commented on src/components/container/recording/Recording.jsx
> +      key={i}
Понял, где видел исправил

2021-11-02 08:25 UTC, Aliaksandrlosich requested changes

2021-11-02 08:25 UTC, Aliaksandrlosich commented on src/components/commons/authForm/logoutForm/LogoutForm.jsx
> +  const buttomText = 'Выйти из профиля';
Такие текстовые константы, и прочие константы выноси из функции компонента. При перерендере функции, или её вызове в другом месте, переменная будет создаваться каждый раз. А если её определить, то только раз, а далее она будет использоваться

2021-11-02 08:25 UTC, Aliaksandrlosich commented on src/components/commons/authForm/logoutForm/LogoutForm.jsx
> +        <h2>Информация о пользователе</h2>
Забыл класс. Так же текст выноси в переменные

2021-11-02 08:25 UTC, Aliaksandrlosich commented on src/components/commons/authForm/registrationForm/RegistrationForm.jsx
> +  const titleText = 'Введите данные для регистрации';
Аналогично. Все константные значения, лучше вынести за функциональную компоненту.

2021-11-02 08:25 UTC, Aliaksandrlosich commented on src/components/commons/reserveItem/modal/hour/Hour.jsx
> +    time.isFree && hourClick(time.hour);
Лучше делать компонент полностью дизейбл, чем уже во время клика думать

2021-11-02 08:25 UTC, Aliaksandrlosich commented on src/components/commons/shedule/Shedule.jsx
> +    return i < 14 && <Day key={day.id} day={day} openModal={openModal} />;
14 стоит вынести в константу. Это мейджик намбер

2021-11-02 08:25 UTC, Aliaksandrlosich commented on src/components/container/instruments/Instruments.jsx
> +      key={i}
Ключ по индексу не хорошо

2021-11-02 08:25 UTC, Aliaksandrlosich commented on src/components/container/main/Main.jsx
> +          {isAuth ? (
Это лучше сделать до jsx

2021-11-02 08:25 UTC, Aliaksandrlosich commented on src/components/routers/Routers.jsx
> +          <Route path='/main' component={Main} />
Реализуй роутер для 404 страницы

2021-11-03 08:42 UTC, SiarheiBalt commented on src/components/routers/Routers.jsx
> +          <Route path='/main' component={Main} />
Реализовал

2021-11-03 08:43 UTC, SiarheiBalt commented on src/components/container/main/Main.jsx
> +          {isAuth ? (
Проглядел. Исправил

2021-11-03 08:44 UTC, SiarheiBalt commented on src/components/container/instruments/Instruments.jsx
> +      key={i}
Где вижу исправляю. Эта компонента у меня в другой ветке

2021-11-03 08:44 UTC, SiarheiBalt commented on src/components/commons/shedule/Shedule.jsx
> +    return i < 14 && <Day key={day.id} day={day} openModal={openModal} />;
Вынес

2021-11-03 08:45 UTC, SiarheiBalt commented on src/components/commons/reserveItem/modal/hour/Hour.jsx
> +    time.isFree && hourClick(time.hour);
Убрал условие, сделал компонент дизейбл

2021-11-03 08:46 UTC, SiarheiBalt commented on src/components/commons/authForm/registrationForm/RegistrationForm.jsx
> +  const titleText = 'Введите данные для регистрации';
Понял, исправил

2021-11-03 08:47 UTC, SiarheiBalt commented on src/components/commons/authForm/logoutForm/LogoutForm.jsx
> +        <h2>Информация о пользователе</h2>
Исправил

2021-11-03 08:47 UTC, SiarheiBalt commented on src/components/commons/authForm/logoutForm/LogoutForm.jsx
> +  const buttomText = 'Выйти из профиля';
Ок, исправляю где вижу

2021-11-10 11:24 UTC, Aliaksandrlosich approved these changes

2021-11-10 11:24 UTC, Aliaksandrlosich commented on src/components/container/instruments/Instruments.jsx
> +        key={i}
Старайся не использовать простые индексы, для ключей

2021-11-10 11:24 UTC, Aliaksandrlosich commented on src/components/container/main/contacts/Contacts.module.css
> +  background-color: whitesmoke;
Почему бы из whitesmoke цвета не сделать переменную? Это у тебя "главный" цвет. Если решишь запилить переключение фона, или редизайн, будет проще, когда у тебя в приложении уже готовые цветовые схемы в переменных

2021-11-10 11:24 UTC, Aliaksandrlosich commented on src/components/container/profile/reserveServicesTable/ReserveServicesTable.jsx
> +      element.type + ' ' + element.name,
`${} ${}` лучше использовать, чем строки слаживать

2021-11-10 11:26 UTC, merged