Instruments
SiarheiBalt/MusicStudio pull request #3
Opened 2021-11-11 06:20 UTC by SiarheiBalt

2021-11-16 12:33 UTC, Aliaksandrlosich requested changes

2021-11-16 12:33 UTC, Aliaksandrlosich commented on src/components/commons/reserveItem/modal/reserveForm/ReserveForm.jsx
>      const isSelected = selectedHours.some((item) => item === time.hour);
тут всё же не item хранится, а hour как я понял.

2021-11-16 12:33 UTC, Aliaksandrlosich commented on src/components/container/instruments/modal/Modal.jsx
> +const text = 'Выберите интересующую дату';
Не понятно откуда текст. Поработай с неймингом

2021-11-16 12:33 UTC, Aliaksandrlosich commented on src/components/container/instruments/modal/Modal.jsx
> +const Modal = ({ closeModal, dates, instrumentId }) => {
Компонента модального окошка должна быть универсальной. В приложение может быть много разных модальных окон А потом в неё вставляешь нужный свой кмпонент в чилдрена.

2021-11-17 18:04 UTC, SiarheiBalt commented on src/components/commons/reserveItem/modal/reserveForm/ReserveForm.jsx
>      const isSelected = selectedHours.some((item) => item === time.hour);
Верно hour, исправил

2021-11-17 18:05 UTC, SiarheiBalt commented on src/components/container/instruments/modal/Modal.jsx
> +const text = 'Выберите интересующую дату';
Изменил

2021-11-18 07:34 UTC, Aliaksandrlosich approved these changes

2021-11-18 07:35 UTC, merged