Requests
SiarheiBalt/MusicStudio pull request #4
Opened 2021-11-18 07:44 UTC by SiarheiBalt

2021-11-24 09:58 UTC, Aliaksandrlosich requested changes

2021-11-24 09:58 UTC, Aliaksandrlosich commented on src/components/commons/preloader/SmallPreloader.jsx
> +export default function SmallPreloader() {
Можно сделать одну компоненту preloader, где в качестве параметра ты передаёшь размер

2021-11-24 09:58 UTC, Aliaksandrlosich commented on src/components/commons/reserveItem/modal/hour/Hour.jsx
> +    if (isAuth) {
Дополнительно добавь, дизейбл для кнопки. Что у пользователя даже желания не было тыкать

2021-11-24 09:58 UTC, Aliaksandrlosich commented on src/components/commons/reserveItem/modal/reserveForm/ReserveForm.jsx
> +    ? 'Кликайте по свободным часам чтобы выбрать время'
Такое описание не очень подходит для приложение с которое предоставлеят услуги. "Выберите свободное время" - Хотя бы так

2021-11-24 09:58 UTC, Aliaksandrlosich commented on src/components/commons/shedule/Shedule.jsx
> +      i < dayInShedule && (
Тяжело читается,

2021-11-24 09:58 UTC, Aliaksandrlosich commented on src/components/container/profile/reserveServicesTable/ReserveServicesTable.jsx
> +      order.type + ' ' + order.name,
Для генерации строк используй `${} ${}`

2021-11-25 15:08 UTC, SiarheiBalt commented on src/components/commons/reserveItem/modal/hour/Hour.jsx
> +    if (isAuth) {
Было добавлено в компоненте hour

2021-11-25 15:08 UTC, SiarheiBalt commented on src/components/commons/preloader/SmallPreloader.jsx
> +export default function SmallPreloader() {
Сделал

2021-11-25 15:11 UTC, SiarheiBalt commented on src/components/commons/reserveItem/modal/reserveForm/ReserveForm.jsx
> +    ? 'Кликайте по свободным часам чтобы выбрать время'
Исправил

2021-11-25 15:18 UTC, SiarheiBalt commented on src/components/commons/shedule/Shedule.jsx
> +      i < dayInShedule && (
Здесь я возвращаю 14 дней для графика. Грамматически неверно написал, исправил на dayOnShedule

2021-11-25 15:28 UTC, SiarheiBalt commented on src/components/container/profile/reserveServicesTable/ReserveServicesTable.jsx
> +      order.type + ' ' + order.name,
Исправил, изменил саму функцию

2021-11-30 08:55 UTC, Aliaksandrlosich requested changes

2021-11-30 08:55 UTC, Aliaksandrlosich commented on src/components/container/profile/reserveServicesTable/ReserveServicesTable.jsx
> +    time: `${reserveTime.sort().join(', ')}`,
Что за махинация? засунь в переменную

2021-12-01 08:55 UTC, SiarheiBalt commented on src/components/container/profile/reserveServicesTable/ReserveServicesTable.jsx
> +    time: `${reserveTime.sort().join(', ')}`,
Создание ряда таблицы. Засунул в переменную

2021-12-03 07:39 UTC, merged