Admin
SiarheiBalt/MusicStudio pull request #5
Opened 2021-11-22 08:10 UTC by SiarheiBalt

2021-11-24 09:20 UTC, Aliaksandrlosich commented on src/components/container/admin/Admin.jsx
> +  const dispatch = useDispatch();
Стоит немного переименовать. И так видно что это диспатч. А вот что за диспатч, и зачем он, не понятно

2021-11-24 09:20 UTC, Aliaksandrlosich commented on src/components/container/admin/adminTable/AdminTable.jsx
> +      <TableRow key={row.date + ' ' + row.time}>
`${date} {time}`- так же не забывай про деструктуризацию

2021-11-24 09:20 UTC, Aliaksandrlosich commented on src/components/container/admin/adminTable/AdminTable.jsx
> +      let user = row.props.children[0].props.children;
Слишком усложнено

2021-11-24 09:20 UTC, Aliaksandrlosich commented on src/components/container/admin/adminTable/AdminTable.jsx
> +    return createData(
Не передавай в функцию так много значений. Лучше передавать обьект, если данные имеют одну сущность. например createDate({owner, ....},<button>

2021-11-24 09:20 UTC, Aliaksandrlosich commented on src/redux/sagas/adminSagas.js
> +
Нейминг файла. Лучше используй request, или api. А не Sagas

2021-11-25 12:05 UTC, SiarheiBalt commented on src/components/container/admin/Admin.jsx
> +  const dispatch = useDispatch();
Переименовал в actionDispatch

2021-11-25 12:05 UTC, SiarheiBalt commented on src/components/container/admin/adminTable/AdminTable.jsx
> +      <TableRow key={row.date + ' ' + row.time}>
Понял, исправлено

2021-11-25 12:08 UTC, SiarheiBalt commented on src/components/container/admin/adminTable/AdminTable.jsx
> +      let user = row.props.children[0].props.children;
Исправил, сделал фильтр для массива с элементами. Было с массивом компонент.

2021-11-25 12:09 UTC, SiarheiBalt commented on src/components/container/admin/adminTable/AdminTable.jsx
> +    return createData(
Исправил, передаю в ф-ю 1 объект

2021-11-25 12:10 UTC, SiarheiBalt commented on src/redux/sagas/adminSagas.js
> +
В это ветке исправлено. Когда соберу приложение поправлю везде

2021-11-30 08:41 UTC, Aliaksandrlosich requested changes

2021-11-30 08:41 UTC, Aliaksandrlosich commented on src/components/container/admin/adminTable/AdminTable.jsx
> +      let user = row.user;
Почему let? значение ж не меняешь. И можно так сделать const {user} = row

2021-11-30 08:41 UTC, Aliaksandrlosich commented on src/components/container/instruments/Instruments.jsx
> +import { ACTIONS } from '../../../redux/constants';
Сделай отдельно для экшенов константы. Что б не тягать за собой все, а импортировать только GET_INSTRUMENTS

2021-11-30 08:41 UTC, Aliaksandrlosich commented on src/components/container/instruments/Instruments.jsx
> +      dates={instrument.dates}
Не забывай про деструктуризацию. С ней код смотрится красивее и чище

2021-11-30 08:41 UTC, Aliaksandrlosich commented on src/redux/reducers/reserveInstrumentsReducer.js
> +        instrument.dates = instrument.dates.map((day) => {
Лучше создавать отдельную переменную, Чем изменять day

2021-12-01 08:18 UTC, SiarheiBalt commented on src/components/container/admin/adminTable/AdminTable.jsx
> +      let user = row.user;
Исправил на конст, применил деструктуризацию

2021-12-01 08:20 UTC, SiarheiBalt commented on src/components/container/instruments/Instruments.jsx
> +import { ACTIONS } from '../../../redux/constants';
Сделал для инструментов (редюсер, сага, компоненты)

2021-12-01 08:20 UTC, SiarheiBalt commented on src/components/container/instruments/Instruments.jsx
> +      dates={instrument.dates}
Ок, исправил

2021-12-01 08:21 UTC, SiarheiBalt commented on src/redux/reducers/reserveInstrumentsReducer.js
> +        instrument.dates = instrument.dates.map((day) => {
Создал переменную

2021-12-03 07:44 UTC, Aliaksandrlosich approved these changes

2021-12-06 08:10 UTC, merged